
;  ▄████████  ▄██████▄  ███▄▄▄▄      ▄████████     ███     
; ███    ███ ███    ███ ███▀▀▀██▄   ███    ███ ▀█████████▄ 
; ███    █▀  ███    ███ ███   ███   ███    █▀     ▀███▀▀██ 
; ███        ███    ███ ███   ███   ███            ███   ▀ 
; ███        ███    ███ ███   ███ ▀███████████     ███     
; ███    █▄  ███    ███ ███   ███          ███     ███     
; ███    ███ ███    ███ ███   ███    ▄█    ███     ███     
; ████████▀   ▀██████▀   ▀█   █▀   ▄████████▀     ▄████▀   
                                                         
;;;-----------------------------------------------------------------------------
;;; These are the constants and enums defined in raylib. 
;;;-----------------------------------------------------------------------------

;;; BUG: No Android buttons defined
;;; FIXME: Add gamepad buttons

(define KEY_APOSTROPHE       39)
(define KEY_COMMA            44)
(define KEY_MINUS            45)
(define KEY_PERIOD           46)
(define KEY_SLASH            47)
(define KEY_ZERO             48)
(define KEY_ONE              49)
(define KEY_TWO              50)
(define KEY_THREE            51)
(define KEY_FOUR             52)
(define KEY_FIVE             53)
(define KEY_SIX              54)
(define KEY_SEVEN            55)
(define KEY_EIGHT            56)
(define KEY_NINE             57)
(define KEY_SEMICOLON        59)
(define KEY_EQUAL            61)
(define KEY_A                65)
(define KEY_B                66)
(define KEY_C                67)
(define KEY_D                68)
(define KEY_E                69)
(define KEY_F                70)
(define KEY_G                71)
(define KEY_H                72)
(define KEY_I                73)
(define KEY_J                74)
(define KEY_K                75)
(define KEY_L                76)
(define KEY_M                77)
(define KEY_N                78)
(define KEY_O                79)
(define KEY_P                80)
(define KEY_Q                81)
(define KEY_R                82)
(define KEY_S                83)
(define KEY_T                84)
(define KEY_U                85)
(define KEY_V                86)
(define KEY_W                87)
(define KEY_X                88)
(define KEY_Y                89)
(define KEY_Z                90)
(define KEY_SPACE            32)
(define KEY_ESCAPE           256)
(define KEY_ENTER            257)
(define KEY_TAB              258)
(define KEY_BACKSPACE        259)
(define KEY_INSERT           260)
(define KEY_DELETE           261)
(define KEY_RIGHT            262)
(define KEY_LEFT             263)
(define KEY_DOWN             264)
(define KEY_UP               265)
(define KEY_PAGE_UP          266)
(define KEY_PAGE_DOWN        267)
(define KEY_HOME             268)
(define KEY_END              269)
(define KEY_CAPS_LOCK        280)
(define KEY_SCROLL_LOCK      281)
(define KEY_NUM_LOCK         282)
(define KEY_PRINT_SCREEN     283)
(define KEY_PAUSE            284)
(define KEY_F1               290)
(define KEY_F2               291)
(define KEY_F3               292)
(define KEY_F4               293)
(define KEY_F5               294)
(define KEY_F6               295)
(define KEY_F7               296)
(define KEY_F8               297)
(define KEY_F9               298)
(define KEY_F10              299)
(define KEY_F11              300)
(define KEY_F12              301)
(define KEY_LEFT_SHIFT       340)
(define KEY_LEFT_CONTROL     341)
(define KEY_LEFT_ALT         342)
(define KEY_LEFT_SUPER       343)
(define KEY_RIGHT_SHIFT      344)
(define KEY_RIGHT_CONTROL    345)
(define KEY_RIGHT_ALT        346)
(define KEY_RIGHT_SUPER      347)
(define KEY_KB_MENU          348)
(define KEY_LEFT_BRACKET     91)
(define KEY_BACKSLASH        92)
(define KEY_RIGHT_BRACKET    93)
(define KEY_GRAVE            96)
(define KEY_KP_0             320)
(define KEY_KP_1             321)
(define KEY_KP_2             322)
(define KEY_KP_3             323)
(define KEY_KP_4             324)
(define KEY_KP_5             325)
(define KEY_KP_6             326)
(define KEY_KP_7             327)
(define KEY_KP_8             328)
(define KEY_KP_9             329)
(define KEY_KP_DECIMAL       330)
(define KEY_KP_DIVIDE        331)
(define KEY_KP_MULTIPLY      332)
(define KEY_KP_SUBTRACT      333)
(define KEY_KP_ADD           334)
(define KEY_KP_ENTER         335)
(define KEY_KP_EQUAL         336)
(define MOUSE_LEFT_BUTTON    0)
(define MOUSE_RIGHT_BUTTON   1)
(define MOUSE_MIDDLE_BUTTON  2)
(define GAMEPAD_PLAYER1      0)
(define GAMEPAD_PLAYER2      1)
(define GAMEPAD_PLAYER3      2)
(define GAMEPAD_PLAYER4      3)
(define FLAG_RESERVED        1)    
(define FLAG_FULLSCREEN_MODE     2)    
(define FLAG_WINDOW_RESIZABLE    4)    
(define FLAG_WINDOW_UNDECORATED  8)    
(define FLAG_WINDOW_TRANSPARENT  16)   
(define FLAG_WINDOW_HIDDEN       128)  
(define FLAG_WINDOW_ALWAYS_RUN   256)  
(define FLAG_MSAA_4X_HINT        32)   
(define FLAG_VSYNC_HINT          64)
